import { DEFINICIONES_PERMISOS } from "@/features/iam/interfaces/iam-constants"
import type { UsuarioIam } from "@/features/iam/interfaces/iam-domain.interface"
import { semillaAceptacionesPoliticas } from "@/features/iam/hooks/iam-page-helpers"

export const USUARIOS_SEMILLA: readonly UsuarioIam[] = [
  {
    id: "u-1",
    nombres: "María Fernanda",
    apellidoPaterno: "López",
    apellidoMaterno: "Ruiz",
    jefeDirecto: "Laura Estrada Campos",
    correoElectronico: "maria.lopez@grupofg.com",
    telefono: "+52 55 1000 1101",
    area: "Capital humano",
    departamento: "Reclutamiento y selección",
    rol: "Administrador",
    activo: true,
    permisos: ["viajes.solicitar", "viajes.aprobar", "admin.usuarios"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2025-11-02T14:30:00.000Z"),
  },
  {
    id: "u-2",
    nombres: "Carlos Eduardo",
    apellidoPaterno: "Núñez",
    apellidoMaterno: "",
    jefeDirecto: "Miguel Ángel Torres Ruiz",
    correoElectronico: "carlos.nunez@grupofg.com",
    telefono: "+52 81 2000 2202",
    area: "Tesorería",
    departamento: "Pagos",
    rol: "Colaborador",
    activo: true,
    permisos: ["viaticos.dispersar", "contabilidad.autorizar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2026-01-10T09:15:00.000Z"),
  },
  {
    id: "u-3",
    nombres: "Ana Lucía",
    apellidoPaterno: "Herrera",
    apellidoMaterno: "Gómez",
    jefeDirecto: "Roberto Salinas Vega",
    correoElectronico: "ana.herrera@grupofg.com",
    telefono: "+52 33 3000 3303",
    area: "Operaciones",
    departamento: "Planeación operativa",
    rol: "Supervisor",
    activo: false,
    permisos: ["viajes.solicitar", "comprobacion.revisar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(false, null),
  },
  {
    id: "u-4",
    nombres: "Roberto",
    apellidoPaterno: "Salinas",
    apellidoMaterno: "Vega",
    jefeDirecto: "Patricia Méndez Ruiz",
    correoElectronico: "roberto.salinas@grupofg.com",
    telefono: "+52 55 4000 4404",
    area: "Dirección financiera",
    departamento: "Dirección general",
    rol: "Super Admin",
    activo: true,
    permisos: DEFINICIONES_PERMISOS.map((p) => p.id),
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2024-06-18T11:00:00.000Z"),
  },
  {
    id: "u-5",
    nombres: "Laura",
    apellidoPaterno: "Estrada",
    apellidoMaterno: "Campos",
    jefeDirecto: "Patricia Méndez Ruiz",
    correoElectronico: "laura.estrada@grupofg.com",
    telefono: "+52 55 5000 5505",
    area: "Capital humano",
    departamento: "Desarrollo organizacional",
    rol: "Administrador",
    activo: true,
    permisos: ["viajes.aprobar", "tarjetas.asignar", "admin.usuarios"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2025-08-22T16:45:00.000Z"),
  },
  {
    id: "u-6",
    nombres: "Miguel Ángel",
    apellidoPaterno: "Torres",
    apellidoMaterno: "Ruiz",
    jefeDirecto: "Patricia Méndez Ruiz",
    correoElectronico: "miguel.torres@grupofg.com",
    telefono: "+52 55 6000 6606",
    area: "Tesorería",
    departamento: "Tesorería corporativa",
    rol: "Administrador",
    activo: true,
    permisos: ["viaticos.dispersar", "contabilidad.autorizar", "comprobacion.revisar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2026-03-01T08:20:00.000Z"),
  },
  {
    id: "u-7",
    nombres: "Ana Karen",
    apellidoPaterno: "Flores",
    apellidoMaterno: "Díaz",
    jefeDirecto: "Laura Estrada Campos",
    correoElectronico: "ana.flores@grupofg.com",
    telefono: "+52 55 7000 7707",
    area: "Administración central",
    departamento: "Contabilidad administrativa",
    rol: "Colaborador",
    activo: true,
    permisos: ["viajes.solicitar", "viajes.aprobar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(false, null),
  },
  {
    id: "u-8",
    nombres: "Diego Armando",
    apellidoPaterno: "Rivas",
    apellidoMaterno: "",
    jefeDirecto: "Karla Jiménez Ríos",
    correoElectronico: "diego.rivas@grupofg.com",
    telefono: "+52 664 8000 8808",
    area: "Ventas",
    departamento: "Ventas nacionales",
    rol: "Colaborador",
    activo: true,
    permisos: ["viajes.solicitar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2025-12-05T13:10:00.000Z"),
  },
  {
    id: "u-9",
    nombres: "Patricia",
    apellidoPaterno: "Méndez",
    apellidoMaterno: "Ruiz",
    jefeDirecto: "Consejo de administración",
    correoElectronico: "patricia.mendez@grupofg.com",
    telefono: "+52 55 9000 9909",
    area: "Dirección financiera",
    departamento: "Presidencia",
    rol: "Super Admin",
    activo: true,
    permisos: ["viajes.aprobar", "contabilidad.autorizar", "admin.usuarios"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2024-01-15T10:00:00.000Z"),
  },
  {
    id: "u-10",
    nombres: "Fernando",
    apellidoPaterno: "Castillo",
    apellidoMaterno: "Leal",
    jefeDirecto: "Patricia Méndez Ruiz",
    correoElectronico: "fernando.castillo@grupofg.com",
    telefono: "+52 442 1010 1010",
    area: "TI",
    departamento: "Infraestructura y seguridad",
    rol: "Administrador",
    activo: true,
    permisos: ["admin.usuarios", "tarjetas.asignar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2026-02-28T12:00:00.000Z"),
  },
  {
    id: "u-11",
    nombres: "Gabriela",
    apellidoPaterno: "Soto",
    apellidoMaterno: "Mireles",
    jefeDirecto: "Roberto Salinas Vega",
    correoElectronico: "gabriela.soto@grupofg.com",
    telefono: "+52 477 1111 1111",
    area: "Legal",
    departamento: "Cumplimiento",
    rol: "Colaborador",
    activo: false,
    permisos: ["viajes.solicitar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2023-09-01T09:00:00.000Z"),
  },
  {
    id: "u-12",
    nombres: "Héctor",
    apellidoPaterno: "Ramírez",
    apellidoMaterno: "Ponce",
    jefeDirecto: "Ana Lucía Herrera Gómez",
    correoElectronico: "hector.ramirez@grupofg.com",
    telefono: "+52 656 1212 1212",
    area: "Logística",
    departamento: "Almacén y distribución",
    rol: "Supervisor",
    activo: true,
    permisos: ["viajes.solicitar", "comprobacion.revisar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2025-10-20T07:30:00.000Z"),
  },
  {
    id: "u-13",
    nombres: "Ivonne",
    apellidoPaterno: "Delgado",
    apellidoMaterno: "Fuentes",
    jefeDirecto: "Miguel Ángel Torres Ruiz",
    correoElectronico: "ivonne.delgado@grupofg.com",
    telefono: "+52 844 1313 1313",
    area: "Compras",
    departamento: "Compras indirectas",
    rol: "Colaborador",
    activo: true,
    permisos: ["viajes.solicitar", "viajes.aprobar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(false, null),
  },
  {
    id: "u-14",
    nombres: "Javier",
    apellidoPaterno: "Ortega",
    apellidoMaterno: "Silva",
    jefeDirecto: "Patricia Méndez Ruiz",
    correoElectronico: "javier.ortega@grupofg.com",
    telefono: "+52 667 1414 1414",
    area: "Auditoría",
    departamento: "Auditoría interna",
    rol: "Colaborador",
    activo: true,
    permisos: ["contabilidad.autorizar", "comprobacion.revisar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2026-01-05T15:40:00.000Z"),
  },
  {
    id: "u-15",
    nombres: "Karla",
    apellidoPaterno: "Jiménez",
    apellidoMaterno: "Ríos",
    jefeDirecto: "Laura Estrada Campos",
    correoElectronico: "karla.jimenez@grupofg.com",
    telefono: "+52 999 1515 1515",
    area: "Marketing",
    departamento: "Mercadotecnia",
    rol: "Colaborador",
    activo: true,
    permisos: ["viajes.solicitar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2025-07-14T11:11:00.000Z"),
  },
  {
    id: "u-16",
    nombres: "Luis Gerardo",
    apellidoPaterno: "Peña",
    apellidoMaterno: "",
    jefeDirecto: "Héctor Ramírez Ponce",
    correoElectronico: "luis.pena@grupofg.com",
    telefono: "+52 614 1616 1616",
    area: "Manufactura",
    departamento: "Producción",
    rol: "Supervisor",
    activo: true,
    permisos: ["viajes.solicitar", "tarjetas.asignar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2025-04-30T06:00:00.000Z"),
  },
  {
    id: "u-17",
    nombres: "Mónica",
    apellidoPaterno: "Vázquez",
    apellidoMaterno: "Lara",
    jefeDirecto: "Luis Gerardo Peña",
    correoElectronico: "monica.vazquez@grupofg.com",
    telefono: "+52 443 1717 1717",
    area: "Calidad",
    departamento: "Control de calidad",
    rol: "Colaborador",
    activo: false,
    permisos: [],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(false, null),
  },
  {
    id: "u-18",
    nombres: "Nicolás",
    apellidoPaterno: "Duarte",
    apellidoMaterno: "Reyes",
    jefeDirecto: "Fernando Castillo Leal",
    correoElectronico: "nicolas.duarte@grupofg.com",
    telefono: "+52 229 1818 1818",
    area: "Innovación",
    departamento: "Producto digital",
    rol: "Colaborador",
    activo: true,
    permisos: ["viajes.solicitar", "viajes.aprobar", "comprobacion.revisar"],
    aceptacionesPoliticas: semillaAceptacionesPoliticas(true, "2026-03-08T09:09:00.000Z"),
  },
]
