import type { FinancialAuthorizationSolicitudPendienteRevision } from "@/features/financial-authorization/interfaces/financial-authorization-solicitud.interface"

export const SOLICITUDES_SEMILLA: FinancialAuthorizationSolicitudPendienteRevision[] =
  [
    {
      id: "sol-001",
      folioSolicitud: "SV-2026-0142",
      resumen: "Seguimiento cliente clave — norte",
      solicitante: "María González",
      correoElectronico: "maria.gonzalez@fgservicios.mx",
      empresa: "FG Servicios",
      area: "Ventas",
      fechaCierreComprobacion: "2026-04-02",
      viajes: [
        {
          id: "v-sol001-1",
          idViaje: "viaje-8821",
          titulo: "Visita cliente — Monterrey",
          destino: "Monterrey, NL",
          periodoInicio: "2026-03-18",
          periodoFin: "2026-03-21",
          movimientosComprobados: [
            {
              id: "mov-a1",
              numeroMovimiento: 12041,
              fecha: "2026-03-19",
              descripcion: "Hotel — hospedaje",
              categoria: "Hospedaje",
              monto: 4280.5,
            },
            {
              id: "mov-a2",
              numeroMovimiento: 12042,
              fecha: "2026-03-20",
              descripcion: "Taxi aeropuerto — hotel",
              categoria: "Transporte local",
              monto: 385.0,
            },
            {
              id: "mov-a3",
              numeroMovimiento: 12043,
              fecha: "2026-03-20",
              descripcion: "Comida con cliente",
              categoria: "Alimentos",
              monto: 1240.75,
            },
          ],
        },
      ],
    },
    {
      id: "sol-002",
      folioSolicitud: "SV-2026-0156",
      resumen: "Capacitación y junta con dirección (un solo envío)",
      solicitante: "Luis Herrera",
      correoElectronico: "luis.herrera@grupofg.mx",
      empresa: "Grupo FG Industrial",
      area: "Operaciones",
      fechaCierreComprobacion: "2026-04-05",
      viajes: [
        {
          id: "v-sol002-1",
          idViaje: "viaje-8844",
          titulo: "Capacitación interna — CDMX",
          destino: "Ciudad de México",
          periodoInicio: "2026-03-25",
          periodoFin: "2026-03-26",
          movimientosComprobados: [
            {
              id: "mov-b1",
              numeroMovimiento: 12102,
              fecha: "2026-03-26",
              descripcion: "Vuelo redondo",
              categoria: "Transporte",
              monto: 6890.0,
            },
            {
              id: "mov-b2",
              numeroMovimiento: 12103,
              fecha: "2026-03-26",
              descripcion: "Uber sede — hotel",
              categoria: "Transporte local",
              monto: 198.5,
            },
          ],
        },
        {
          id: "v-sol002-2",
          idViaje: "viaje-8845",
          titulo: "Junta con dirección — CDMX",
          destino: "Ciudad de México",
          periodoInicio: "2026-03-26",
          periodoFin: "2026-03-27",
          movimientosComprobados: [
            {
              id: "mov-b3",
              numeroMovimiento: 12104,
              fecha: "2026-03-27",
              descripcion: "Comida de trabajo — junta",
              categoria: "Alimentos",
              monto: 980.0,
            },
          ],
        },
      ],
    },
    {
      id: "sol-003",
      folioSolicitud: "SV-2026-0161",
      resumen: "Auditoría de campo — occidente",
      solicitante: "Ana Ruiz",
      correoElectronico: "ana.ruiz@alianza.com.mx",
      empresa: "Alianza Eléctrica",
      area: "Logística",
      fechaCierreComprobacion: "2026-04-08",
      viajes: [
        {
          id: "v-sol003-1",
          idViaje: "viaje-8850",
          titulo: "Auditoría de campo — Guadalajara",
          destino: "Guadalajara, JAL",
          periodoInicio: "2026-04-01",
          periodoFin: "2026-04-04",
          movimientosComprobados: [
            {
              id: "mov-c1",
              numeroMovimiento: 12188,
              fecha: "2026-04-02",
              descripcion: "Renta de auto",
              categoria: "Transporte",
              monto: 3150.0,
            },
            {
              id: "mov-c2",
              numeroMovimiento: 12189,
              fecha: "2026-04-03",
              descripcion: "Casetas y estacionamiento",
              categoria: "Casetas",
              monto: 642.3,
            },
            {
              id: "mov-c3",
              numeroMovimiento: 12190,
              fecha: "2026-04-03",
              descripcion: "Cena equipo auditoría",
              categoria: "Alimentos",
              monto: 2180.0,
            },
            {
              id: "mov-c4",
              numeroMovimiento: 12191,
              fecha: "2026-04-04",
              descripcion: "Hospedaje fin de viaje",
              categoria: "Hospedaje",
              monto: 1950.0,
            },
          ],
        },
      ],
    },
  ]

export const COMENTARIO_USUARIO_AL_COMPROBAR_MOCK: Record<string, string> = {
  "mov-a1":
    "Factura a nombre de la empresa; hospedaje acordado con el cliente para cierre comercial.",
  "mov-a2": "Trayecto aeropuerto–hotel; tarifa estándar sin propina en ticket.",
  "mov-a3": "Comida de trabajo con cliente; se solicitó factura con IVA desglosado.",
  "mov-b1": "Vuelo en tarifa corporativa; equipaje de mano únicamente.",
  "mov-b2": "Traslado sede–hotel según política de zona metropolitana.",
  "mov-b3": "Comida de junta con dirección; participantes internos y externos.",
  "mov-c1": "Renta de unidad para recorridos de auditoría en sitio.",
  "mov-c2": "Casetas y estacionamiento en ruta; tickets conservados.",
  "mov-c3": "Cena de equipo de auditoría; no incluye bebidas alcohólicas.",
  "mov-c4": "Última noche de hospedaje; check-out según itinerario.",
}
