import {
  Banknote,
  Car,
  ClipboardCheck,
  CreditCard,
  FilePlus,
  FileText,
  Fuel,
  Receipt,
} from "lucide-react"

import type { HomeMenuOption } from "@/features/home/interfaces/home-menu-option.interface"

export const HOME_MENU_OPTIONS: HomeMenuOption[] = [
  {
    id: 1,
    title: "Crear Solicitud",
    description: "Genera una nueva solicitud de viáticos",
    icon: FilePlus,
    color: "from-blue-500 to-blue-600",
    shadowColor: "shadow-blue-500/25",
    delay: 100,
    href: "/travel-request",
  },
  {
    id: 2,
    title: "Solicitudes de Viáticos",
    description: "Consulta el estado de tus solicitudes",
    icon: FileText,
    color: "from-emerald-500 to-emerald-600",
    shadowColor: "shadow-emerald-500/25",
    delay: 150,
    href: "/travel-approval",
  },
  {
    id: 3,
    title: "Dispersión de Viáticos",
    description: "Gestiona la distribución de fondos",
    icon: Banknote,
    color: "from-amber-500 to-amber-600",
    shadowColor: "shadow-amber-500/25",
    delay: 200,
    href: "/dispersion-travel",
  },
  {
    id: 4,
    title: "Autorización Contable",
    description: "Aprueba movimientos contables",
    icon: ClipboardCheck,
    color: "from-violet-500 to-violet-600",
    shadowColor: "shadow-violet-500/25",
    delay: 250,
    href: "/menu-accounting",
  },
  {
    id: 5,
    title: "Asignación de Tarjeta",
    description: "Administra tarjetas corporativas",
    icon: CreditCard,
    color: "from-rose-500 to-rose-600",
    shadowColor: "shadow-rose-500/25",
    delay: 300,
    href: "/card-assignment",
  },
  {
    id: 6,
    title: "Comprobación de Viáticos",
    description: "Verifica y comprueba gastos",
    icon: Receipt,
    color: "from-cyan-500 to-cyan-600",
    shadowColor: "shadow-cyan-500/25",
    delay: 350,
    href: "/travel-expenses",
  },
  {
    id: 7,
    title: "Módulo de Gasolina",
    description: "Control de consumo de combustible",
    icon: Fuel,
    color: "from-orange-500 to-orange-600",
    shadowColor: "shadow-orange-500/25",
    delay: 400,
    href: "#",
  },
  {
    id: 8,
    title: "Reserva de Autos",
    description: "Gestiona reservas de vehículos corporativos",
    icon: Car,
    color: "from-indigo-500 to-indigo-600",
    shadowColor: "shadow-indigo-500/25",
    delay: 450,
    href: "/car-reservation",
  },
] as const
